import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";

export default function (pi: ExtensionAPI) {
  const vllmCompat = {
    supportsDeveloperRole: false,
    supportsStore: false,
    supportsReasoningEffort: false,
    maxTokensField: "max_tokens" as const,
    supportsStrictMode: false,
  };

  const qwenCompat = {
    supportsDeveloperRole: false,
    supportsStore: false,
    supportsReasoningEffort: false,
    maxTokensField: "max_tokens" as const,
    supportsStrictMode: true,
    thinkingFormat: "qwen",
  };

  // Register new provider with models from Chat AI Academic Cloud
  pi.registerProvider("academiccloud", {
    baseUrl: "https://chat-ai.academiccloud.de/v1",
    apiKey: "ACADEMICCLOUD_API_KEY",
    api: "openai-completions",
    models: [
      // Text models
      {
        id: "apertus-70b-instruct-2509",
        name: "Apertus 70B Instruct 2509",
        reasoning: false,
        input: ["text"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 65000,
        maxTokens: 8192,
        compat: vllmCompat,
      },
      {
        id: "meta-llama-3.1-8b-instruct",
        name: "Llama 3.1 8B Instruct",
        reasoning: false,
        input: ["text"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 128000,
        maxTokens: 8192,
        compat: vllmCompat,
      },
      {
        id: "llama-3.3-70b-instruct",
        name: "Llama 3.3 70B Instruct",
        reasoning: false,
        input: ["text"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 128000,
        maxTokens: 8192,
        compat: vllmCompat,
      },
      // Not in HTML documentation
      // {
      //   id: "llama-3.1-sauerkrautlm-70b-instruct",
      //   name: "Llama 3.1 SauerkrautLM 70B (German)",
      //   reasoning: false,
      //   input: ["text"],
      //   cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
      //   contextWindow: 128000,
      //   maxTokens: 8192,
      //   compat: vllmCompat,
      // },
      {
        id: "qwen3-30b-a3b-instruct-2507",
        name: "Qwen 3 30B A3B Instruct 2507",
        reasoning: true,
        input: ["text"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 256000,
        maxTokens: 8192,
        compat: qwenCompat,
        thinkingFormat: "qwen",
      },
      {
        id: "qwen3-30b-a3b-thinking-2507",
        name: "Qwen 3 30B A3B Thinking 2507",
        reasoning: true,
        input: ["text"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 256000,
        maxTokens: 8192,
        compat: vllmCompat,
        thinkingFormat: "qwen",
      },
      {
        id: "qwen3-32b",
        name: "Qwen 3 32B",
        reasoning: true,
        input: ["text"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 32000,
        maxTokens: 8192,
        compat: qwenCompat,
        thinkingFormat: "qwen",
      },
      {
        id: "glm-4.7",
        name: "GLM-4.7",
        reasoning: false,
        input: ["text"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 200000,
        maxTokens: 8192,
        compat: vllmCompat,
      },
      {
        id: "teuken-7b-instruct-research",
        name: "Teuken 7B Instruct Research (European Languages)",
        reasoning: false,
        input: ["text"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 128000,
        maxTokens: 8192,
        compat: vllmCompat,
      },
      // Reasoning models
      {
        id: "deepseek-r1-distill-llama-70b",
        name: "DeepSeek R1 Distill Llama 70B",
        reasoning: true,
        input: ["text"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 32000,
        maxTokens: 8192,
        compat: vllmCompat,
      },
      {
        id: "qwen3-235b-a22b",
        name: "Qwen 3 235B A22B Thinking",
        reasoning: true,
        input: ["text"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 222000,
        maxTokens: 8192,
        compat: vllmCompat,
        thinkingFormat: "qwen",
      },
      // Coding models
      {
        id: "devstral-2-123b-instruct-2512",
        name: "Devstral 2 123B Instruct 2512 (Coding)",
        reasoning: false,
        input: ["text"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 256000,
        maxTokens: 8192,
        compat: vllmCompat,
      },
      {
        id: "qwen3-coder-30b-a3b-instruct",
        name: "Qwen 3 Coder 30B A3B Instruct",
        reasoning: true,
        input: ["text"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 256000,
        maxTokens: 8192,
        compat: qwenCompat,
        thinkingFormat: "qwen",
      },
      {
        id: "openai-gpt-oss-120b",
        name: "OpenAI GPT OSS 120B",
        reasoning: false,
        input: ["text"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 128000,
        maxTokens: 8192,
        compat: vllmCompat,
      },
      // Vision models (text + image)
      {
        id: "gemma-3-27b-it",
        name: "Gemma 3 27B Instruct (Vision)",
        reasoning: false,
        input: ["text", "image"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 128000,
        maxTokens: 8192,
        compat: vllmCompat,
      },
      {
        id: "internvl3.5-30b-a3b",
        name: "InternVL 3.5 30B A3B (Vision)",
        reasoning: false,
        input: ["text", "image"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 40000,
        maxTokens: 8192,
        compat: vllmCompat,
      },
      {
        id: "medgemma-27b-it",
        name: "MedGemma 27B Instruct (Medical, Vision)",
        reasoning: false,
        input: ["text", "image"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 128000,
        maxTokens: 8192,
        compat: vllmCompat,
      },
      {
        id: "mistral-large-3-675b-instruct-2512",
        name: "Mistral Large 3 675B Instruct 2512 (Vision)",
        reasoning: false,
        input: ["text", "image"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 256000,
        maxTokens: 8192,
        compat: vllmCompat,
      },
      {
        id: "qwen3-vl-30b-a3b-instruct",
        name: "Qwen 3 VL 30B A3B Instruct (Vision)",
        reasoning: true,
        input: ["text", "image"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 262000,
        maxTokens: 8192,
        compat: qwenCompat,
        thinkingFormat: "qwen",
      },
      {
        id: "qwen3-omni-30b-a3b-instruct",
        name: "Qwen 3 Omni 30B A3B Instruct (Multimodal)",
        reasoning: true,
        input: ["text", "image"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 256000,
        maxTokens: 8192,
        compat: qwenCompat,
        thinkingFormat: "qwen",
      },
      {
        id: "qwen3.5-122b-a10b",
        name: "Qwen 3.5 122B A10B (Vision)",
        reasoning: true,
        input: ["text", "image"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 256000,
        maxTokens: 8192,
        compat: qwenCompat,
      },
      {
        id: "qwen3.5-27b",
        name: "Qwen 3.5 27B (Vision)",
        reasoning: true,
        input: ["text", "image"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 256000,
        maxTokens: 8192,
        compat: qwenCompat,
      },
      {
        id: "qwen3.5-35b-a3b",
        name: "Qwen 3.5 35B A3B (Vision)",
        reasoning: true,
        input: ["text", "image"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 256000,
        maxTokens: 8192,
        compat: qwenCompat,
      },
      {
        id: "qwen3.5-397b-a17b",
        name: "Qwen 3.5 397B A17B (Vision)",
        reasoning: true,
        input: ["text", "image"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 256000,
        maxTokens: 8192,
        compat: qwenCompat,
      },
      {
        id: "e5-mistral-7b-instruct",
        name: "E5 Mistral 7B Instruct (Embeddings)",
        reasoning: false,
        input: ["text"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 4096,
        maxTokens: 8192,
        compat: vllmCompat,
      },
    ]
  });
}
